
    create table Categoria (
        Categorias varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Ciudades (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        provincia_id bigint,
        primary key (id)
    )

    create table Ciudades_Proveedores (
        Ciudades_id bigint not null,
        proveedores_id integer not null
    )

    create table Compras (
        id bigint generated by default as identity (start with 1),
        cantidad_presupuesto integer,
        fecha varbinary(255),
        monto_total double,
        requiere_presupuesto boolean,
        validado boolean,
        entidad_id bigint,
        moneda_id bigint,
        presupuesto_seleccionado_id bigint,
        proveedor_id integer,
        primary key (id)
    )

    create table Compras_Etiquetas (
        Compras_id bigint not null,
        etiquetas_id bigint not null
    )

    create table Compras_Usuarios (
        Compras_id bigint not null,
        usuario_id bigint not null
    )

    create table Documentos_comerciales (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Documentos_comerciales_compras (
        compra_id integer not null,
        documento_comercial_id integer not null,
        numero integer not null,
        primary key (compra_id, documento_comercial_id)
    )

    create table Entidad (
        tipo_entidad varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        categoria_entidad_juridica integer,
        clasificacion_afip integer,
        codigoIGJ varchar(255),
        cuit varchar(255),
        direccion_postal varchar(255),
        nombre_ficticio varchar(255),
        razon_social varchar(255),
        nombre varchar(255),
        categoria_entidad_id bigint,
        entidad_juridica_id bigint,
        primary key (id)
    )

    create table Etiquetas (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Etiquetas_Proveedores (
        Etiquetas_id bigint not null,
        proveedores_id integer not null
    )

    create table Items (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Items_de_compra (
        compra_id bigint not null,
        item_id bigint not null,
        cantidad integer not null,
        precio double,
        moneda_id bigint,
        numero integer,
        nombre integer,
        primary key (compra_id, item_id)
    )

    create table Items_del_presupuesto (
        item_id bigint not null,
        presupuesto_id bigint not null,
        cantidad integer not null,
        precio double,
        primary key (item_id, presupuesto_id)
    )

    create table Medios_de_pago_compra (
        compra_id integer not null,
        medio_pago_id integer not null,
        numero integer not null,
        tipo_medio_pago_id bigint,
        primary key (compra_id, medio_pago_id)
    )

    create table Monedas (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Paises (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        moneda_id bigint,
        region_id bigint,
        primary key (id)
    )

    create table Presupuestos (
        id bigint generated by default as identity (start with 1),
        fecha varbinary(255),
        documentoComercial_id bigint,
        proveedor_id integer,
        compra_id bigint,
        primary key (id)
    )

    create table Proveedores (
        id integer generated by default as identity (start with 1),
        altura integer not null,
        apellido varchar(255),
        calle varchar(255),
        cuit varchar(255),
        dni varchar(255),
        nombre varchar(255),
        piso varchar(255),
        razon_social varchar(255),
        ciudad_id bigint,
        primary key (id)
    )

    create table Provincias (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        pais_id bigint,
        primary key (id)
    )

    create table Regiones (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Tipos_medio_de_pago (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Usuarios (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        hash varchar(255),
        primary key (id)
    )

    alter table Ciudades 
        add constraint FK_jqq4ce9cm763kej9skp9kefxy 
        foreign key (provincia_id) 
        references Provincias

    alter table Ciudades_Proveedores 
        add constraint FK_e09fgooslnop5i01tn4u7gjed 
        foreign key (proveedores_id) 
        references Proveedores

    alter table Ciudades_Proveedores 
        add constraint FK_qe4d74qvx67xafwir64hor7u3 
        foreign key (Ciudades_id) 
        references Ciudades

    alter table Compras 
        add constraint FK_r7lg6tbohpcp3rxwn60k8iku0 
        foreign key (entidad_id) 
        references Entidad

    alter table Compras 
        add constraint FK_pwqjjeu6bnyll3d7gckmnsigu 
        foreign key (moneda_id) 
        references Monedas

    alter table Compras 
        add constraint FK_3h9md2lr4qetxkefc05bnsfuf 
        foreign key (presupuesto_seleccionado_id) 
        references Presupuestos

    alter table Compras 
        add constraint FK_18kx33qmwsj9h49hxwuttuphl 
        foreign key (proveedor_id) 
        references Proveedores

    alter table Compras_Etiquetas 
        add constraint FK_kq3juhlch0jgmmkx3hwjyijox 
        foreign key (etiquetas_id) 
        references Etiquetas

    alter table Compras_Etiquetas 
        add constraint FK_eg0ob2dg85234rq0kaiua0osj 
        foreign key (Compras_id) 
        references Compras

    alter table Compras_Usuarios 
        add constraint FK_r457a3ey65a5fspncfg7k1qsc 
        foreign key (usuario_id) 
        references Usuarios

    alter table Compras_Usuarios 
        add constraint FK_too5krgj6bqxdoapqdtpp5at2 
        foreign key (Compras_id) 
        references Compras

    alter table Documentos_comerciales_compras 
        add constraint FK_tgvy7o78klna6ol8jg6tlpw3o 
        foreign key (compra_id) 
        references Compras

    alter table Documentos_comerciales_compras 
        add constraint FK_sqov6ie28j7pey77h62yy8u12 
        foreign key (documento_comercial_id) 
        references Documentos_comerciales

    alter table Entidad 
        add constraint FK_3g7enh26wmig4nw23x1euonsx 
        foreign key (categoria_entidad_id) 
        references Categoria

    alter table Entidad 
        add constraint FK_hpaa53wuccwmu8325wwxrq7ka 
        foreign key (entidad_juridica_id) 
        references Entidad

    alter table Etiquetas_Proveedores 
        add constraint FK_729c3n5m3nmhbl02cgn7s23ib 
        foreign key (proveedores_id) 
        references Proveedores

    alter table Etiquetas_Proveedores 
        add constraint FK_t4of2hqmed09v6jpp3myx6x1 
        foreign key (Etiquetas_id) 
        references Etiquetas

    alter table Items_de_compra 
        add constraint FK_e8jvidxfc4b5lvwng1fhoruts 
        foreign key (moneda_id) 
        references Monedas

    alter table Items_de_compra 
        add constraint FK_cr6itc7jma2nu1hp4ahxalgbb 
        foreign key (compra_id) 
        references Compras

    alter table Items_de_compra 
        add constraint FK_8vj3dq64liax1ncqm0y9f408k 
        foreign key (item_id) 
        references Items

    alter table Items_del_presupuesto 
        add constraint FK_lb02adehdaua28ngfuuayuigh 
        foreign key (presupuesto_id) 
        references Presupuestos

    alter table Items_del_presupuesto 
        add constraint FK_q8fdy5b19we7wxaliopf508mm 
        foreign key (item_id) 
        references Items

    alter table Medios_de_pago_compra 
        add constraint FK_j7xawmcfyfq4ra4me88m7s1ej 
        foreign key (compra_id) 
        references Compras

    alter table Medios_de_pago_compra 
        add constraint FK_p4qanl2ljqc0hg9evo27yqgpw 
        foreign key (tipo_medio_pago_id) 
        references Tipos_medio_de_pago

    alter table Paises 
        add constraint FK_ooca51cq15m6ul5tyb18riaor 
        foreign key (moneda_id) 
        references Monedas

    alter table Paises 
        add constraint FK_485f5at7pa40c2ug15kwj0n17 
        foreign key (region_id) 
        references Regiones

    alter table Presupuestos 
        add constraint FK_5w17c1u3jf6tbkf9phukiive0 
        foreign key (documentoComercial_id) 
        references Documentos_comerciales

    alter table Presupuestos 
        add constraint FK_tia29gihl1h86vpbaq5hc1996 
        foreign key (proveedor_id) 
        references Proveedores

    alter table Presupuestos 
        add constraint FK_hju37tsvb77rqpat4kk3uxwrs 
        foreign key (compra_id) 
        references Compras

    alter table Proveedores 
        add constraint FK_ek7xqbkb9bfvq6dfoau9iomy0 
        foreign key (ciudad_id) 
        references Ciudades

    alter table Provincias 
        add constraint FK_59a7otbmp8yj5k1c4f64nr89m 
        foreign key (pais_id) 
        references Paises
