
    create table Compras (
        id bigint generated by default as identity (start with 1),
        entidad_id integer not null,
        entidad_tipo integer not null,
        fecha varbinary(255),
        monto_total double,
        proveedor_id integer,
        primary key (id)
    )

    create table Items (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table JoinEntidadBase (
        nombre varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table JoinEntidadJuridica (
        codigoIGJ varchar(255),
        cuit varchar(255),
        direccion_postal varchar(255),
        nombreFicticio varchar(255),
        razonSocial varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table Medios_de_pago (
        compra_id integer not null,
        tipo_medio_pago_id integer not null,
        numero integer not null,
        primary key (compra_id, tipo_medio_pago_id)
    )

    create table Proveedores (
        id integer generated by default as identity (start with 1),
        apellido varchar(255),
        codigo_postal varchar(255),
        cuit varchar(255),
        dni varchar(255),
        nombre varchar(255),
        razon_social varchar(255),
        primary key (id)
    )

    create table SingleEntidad (
        tipo_entidad varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        codigoIGJ varchar(255),
        cuit varchar(255),
        direccion_postal varchar(255),
        nombreFicticio varchar(255),
        razonSocial varchar(255),
        entidad_juridica_id bigint,
        primary key (id)
    )

    create table TPCEntidadBase (
        id bigint not null,
        nombre varchar(255),
        primary key (id)
    )

    create table TPCEntidadJuridica (
        id bigint not null,
        codigoIGJ varchar(255),
        cuit varchar(255),
        direccion_postal varchar(255),
        nombreFicticio varchar(255),
        razonSocial varchar(255),
        primary key (id)
    )

    create table Tipos_documentos_comerciales (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Tipos_medio_de_pago (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table documentos_comerciales (
        id integer generated by default as identity (start with 1),
        numero integer not null,
        tipo_documento_comercial_id bigint,
        compra_id bigint,
        primary key (id)
    )

    create table entidad_join (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table items_de_compra (
        compra_id bigint not null,
        item_id bigint not null,
        cantidad integer not null,
        monto double,
        nombre integer,
        numero integer,
        primary key (compra_id, item_id)
    )

    alter table Compras 
        add constraint FK_18kx33qmwsj9h49hxwuttuphl 
        foreign key (proveedor_id) 
        references Proveedores

    alter table JoinEntidadBase 
        add constraint FK_l098jv78rkgmtmvjo2qg8la32 
        foreign key (id) 
        references entidad_join

    alter table JoinEntidadJuridica 
        add constraint FK_iec0ybanda1dpj96qwi4iyc54 
        foreign key (id) 
        references entidad_join

    alter table Medios_de_pago 
        add constraint FK_to2nos7k20rvonoutl7n13i01 
        foreign key (tipo_medio_pago_id) 
        references Tipos_medio_de_pago

    alter table Medios_de_pago 
        add constraint FK_rnr13u298xeq0sfekmo0987ni 
        foreign key (compra_id) 
        references Compras

    alter table SingleEntidad 
        add constraint FK_nr8cyb5jreodfvolfmshp1idt 
        foreign key (entidad_juridica_id) 
        references SingleEntidad

    alter table documentos_comerciales 
        add constraint FK_odyuxsfbpho1fjmmg20vettoh 
        foreign key (tipo_documento_comercial_id) 
        references Tipos_documentos_comerciales

    alter table documentos_comerciales 
        add constraint FK_mlcgc4te2n7kvfliw4kmfyva6 
        foreign key (compra_id) 
        references Compras

    alter table items_de_compra 
        add constraint FK_adckyq3hci8k94pif3gxh191g 
        foreign key (item_id) 
        references Items

    alter table items_de_compra 
        add constraint FK_8sq3w3jks63ge3y225gkn8r9f 
        foreign key (compra_id) 
        references Compras

    create sequence hibernate_sequence start with 1
